
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ptn = 22;
  public static final int llcierra = 29;
  public static final int tienda = 5;
  public static final int coma = 13;
  public static final int igual = 12;
  public static final int de = 19;
  public static final int iniciou = 3;
  public static final int corr = 35;
  public static final int llabre = 28;
  public static final int iden = 16;
  public static final int menos = 11;
  public static final int EOF = 0;
  public static final int pyc = 25;
  public static final int mas = 31;
  public static final int producto = 6;
  public static final int verdadero = 7;
  public static final int error = 1;
  public static final int pabre = 26;
  public static final int barra = 30;
  public static final int or = 34;
  public static final int rq = 21;
  public static final int multiplica = 32;
  public static final int req = 2;
  public static final int pcierra = 27;
  public static final int crearu = 4;
  public static final int falso = 8;
  public static final int donde = 20;
  public static final int usuario = 24;
  public static final int and = 33;
  public static final int n = 23;
  public static final int dolar = 10;
  public static final int extraer = 18;
  public static final int get = 9;
  public static final int query = 17;
  public static final int valorNumerico = 14;
  public static final int cadena = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "req",
  "iniciou",
  "crearu",
  "tienda",
  "producto",
  "verdadero",
  "falso",
  "get",
  "dolar",
  "menos",
  "igual",
  "coma",
  "valorNumerico",
  "cadena",
  "iden",
  "query",
  "extraer",
  "de",
  "donde",
  "rq",
  "ptn",
  "n",
  "usuario",
  "pyc",
  "pabre",
  "pcierra",
  "llabre",
  "llcierra",
  "barra",
  "mas",
  "multiplica",
  "and",
  "or",
  "corr"
  };
}

