
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Anallizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int curso = 4;
  public static final int na = 23;
  public static final int dosPuntos = 30;
  public static final int coma = 31;
  public static final int igual = 29;
  public static final int abre = 28;
  public static final int docente = 5;
  public static final int bordes = 26;
  public static final int ponderacion = 11;
  public static final int estudiante = 10;
  public static final int semestre = 7;
  public static final int cierra = 36;
  public static final int seccion = 6;
  public static final int cv = 21;
  public static final int ct = 20;
  public static final int porcentaje = 33;
  public static final int EOF = 0;
  public static final int verdadero = 18;
  public static final int error = 1;
  public static final int escuela = 3;
  public static final int rr = 15;
  public static final int valor = 12;
  public static final int rp = 16;
  public static final int cuerpo = 9;
  public static final int cc = 22;
  public static final int id = 35;
  public static final int falso = 19;
  public static final int logo = 25;
  public static final int estilo = 27;
  public static final int re = 17;
  public static final int ra = 14;
  public static final int reportes = 13;
  public static final int bar = 37;
  public static final int encabezado = 2;
  public static final int nr = 24;
  public static final int valorNumerico = 32;
  public static final int año = 8;
  public static final int cadena = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "encabezado",
  "escuela",
  "curso",
  "docente",
  "seccion",
  "semestre",
  "año",
  "cuerpo",
  "estudiante",
  "ponderacion",
  "valor",
  "reportes",
  "ra",
  "rr",
  "rp",
  "re",
  "verdadero",
  "falso",
  "ct",
  "cv",
  "cc",
  "na",
  "nr",
  "logo",
  "bordes",
  "estilo",
  "abre",
  "igual",
  "dosPuntos",
  "coma",
  "valorNumerico",
  "porcentaje",
  "cadena",
  "id",
  "cierra",
  "bar"
  };
}

