
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pyc = 10;
  public static final int req = 2;
  public static final int multiplica = 17;
  public static final int cadena = 8;
  public static final int valorNumerico = 7;
  public static final int llabre = 13;
  public static final int coma = 6;
  public static final int pabre = 11;
  public static final int menos = 4;
  public static final int pcierra = 12;
  public static final int corr = 18;
  public static final int igual = 5;
  public static final int EOF = 0;
  public static final int dolar = 3;
  public static final int llcierra = 14;
  public static final int error = 1;
  public static final int barra = 15;
  public static final int mas = 16;
  public static final int iden = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "req",
  "dolar",
  "menos",
  "igual",
  "coma",
  "valorNumerico",
  "cadena",
  "iden",
  "pyc",
  "pabre",
  "pcierra",
  "llabre",
  "llcierra",
  "barra",
  "mas",
  "multiplica",
  "corr"
  };
}

